name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - branch-a
  pull_request:
    branches:
      - main
      - branch-a

jobs:
  build:
    runs-on: ubuntu-latest # OS environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Ensure this matches your Node.js version

      - name: Install dependencies
        run: npm ci # Clean install based on package-lock.json

      - name: Fix vulnerabilities
        run: npm audit fix # Attempt to fix vulnerabilities

      - name: Run tests
        run: npm test -- --verbose # Verbose output for debugging

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploy step is not configured yet. Configure this based on your deployment provider."
